# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

target 'PushNotifications' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PushNotifications
  pod 'Firebase/Analytics' # Google Analytics
  pod 'FirebaseMessaging'


  target 'PushNotificationsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PushNotificationsUITests' do
    # Pods for testing
  end

end
